[app]
name = "cmdb"
key  = "this is your app key"

[app.http]
host = "0.0.0.0"
port = "8050"

[app.grpc]
host = "0.0.0.0"
port = "18050"




[mysql]
host = "127.0.0.1"
port = "3306"
database = "test"
username = "root"
password = "1234567890"



[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"